### ISSUE TITLE
Export PNG & JPEG produce blank images

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rambaut/figtree#75]
```
Export PNG & JPEG produce blank images
```

Original issue reported on code.google.com by `ramb...@gmail.com` on 4 Jul 2014 at 6:45

**Comment by lczech** [comment]
This might be related to a "weirdness" I observed when saving to svg: The tree being saved is not within svg document boundaries, but slightly outside of it. In case of svg, this is not a big issue, because the data is still there and moving the tree into the document boundaries is possible. In case of jpg, however, this would result in empty files.

**Comment by afreem16** [comment]
I have found that if 'expansion' slider is in use for circular trees, the program will not export. going back to a linear tree and resetting expansion to 0 can allow for export of png files for circular trees.
